# Generated by Django 5.0.7 on 2024-07-21 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="title")),
                ("slug", models.SlugField(verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                ("rate", models.IntegerField(verbose_name="rate")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="is published"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "db_table": "posts",
                "indexes": [
                    models.Index(fields=["slug"], name="posts_slug_6da55a_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                check=models.Q(("rate__gte", 1), ("rate__lte", 10)),
                name="chk_posts_rate",
            ),
        ),
    ]
