# Generated by Django 5.0.7 on 2024-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="title")),
                ("slug", models.SlugField(max_length=256, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="is published"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
                "db_table": "posts",
                "permissions": [("can_publish_posts", "Can publish posts")],
            },
        ),
    ]
