# Generated by Django 5.0.7 on 2024-07-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="rate",
            field=models.IntegerField(default=0, verbose_name="rate"),
        ),
    ]
