# Generated by Django 5.0.7 on 2024-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=256, verbose_name="slug"),
        ),
    ]
