# Generated by Django 5.0.7 on 2024-07-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "€"), ("USD", "$"), ("ALL", "L")],
                        default="EUR",
                        max_length=255,
                    ),
                ),
                ("stripe_product_id", models.CharField(blank=True, max_length=100)),
                ("stripe_price_id", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="products")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "db_table": "pictures",
            },
        ),
    ]
